[project]
name = "price-monitoring"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.0",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
]
